Repository laterpay/laterpay-wordpress-plugin, pull requests merged in 2018-10, with the labels that each got.

#988 Version Update 2.1.0
  composer.json
  gulpfile.js
  laterpay/README.txt
  laterpay/languages/laterpay-de_DE.mo
  laterpay/languages/laterpay-de_DE.po
  laterpay/languages/laterpay.po
  laterpay/laterpay.php
  package.json
Labels: v2.1.0

#1004 Fix issue with account setup warning shown in LIVE mode
  laterpay/views/backend/partials/post-pricing-form.php
Labels: v2.1.1

#1003 Refactor code - Pricing Behaviour
  laterpay/application/Controller/Admin/Post/Column.php
  laterpay/application/Controller/Frontend/Post.php
  laterpay/application/Helper/Pricing.php
  laterpay/application/Module/Purchase.php
  laterpay/application/Module/TimePasses.php
  laterpay/views/backend/partials/post-pricing-form.php
  ruleset.xml
Labels: v2.1.1

#1017 Hide price edit section
  laterpay/application/Controller/Admin/Post/Metabox.php
  laterpay/asset_sources/js/laterpay-post-edit.js
  laterpay/views/backend/partials/post-pricing-form.php
Labels: v2.1.1

#997 Enable all default editor configuration in teaser metabox
  laterpay/application/Controller/Admin/Post/Metabox.php
Labels: v2.2.0

#1005 Add download widget shortcode, Udpate code to avoid cross origin issue
  laterpay/application/Controller/Frontend/Shortcode.php
  laterpay/application/Core/Bootstrap.php
  laterpay/asset_sources/js/laterpay-post-view.js
Labels: v2.1.1

#1030 Tag 2.2.0
  composer.json
  composer.lock
  gulpfile.js
  laterpay/README.txt
  laterpay/application/Controller/Admin/Account.php
  laterpay/application/Controller/Admin/Post/Column.php
  laterpay/application/Controller/Admin/Post/Metabox.php
  laterpay/application/Controller/Admin/Settings.php
  laterpay/application/Controller/Frontend/Post.php
  laterpay/application/Controller/Frontend/Shortcode.php
  laterpay/application/Controller/Install.php
  laterpay/application/Core/Bootstrap.php
  laterpay/application/Helper/Config.php
  laterpay/application/Helper/Post.php
  laterpay/application/Helper/Pricing.php
  laterpay/application/Helper/View.php
  laterpay/application/Module/Appearance.php
  laterpay/application/Module/Purchase.php
  laterpay/application/Module/TimePasses.php
  laterpay/asset_sources/js/laterpay-backend-options.js
  laterpay/asset_sources/js/laterpay-backend-pricing.js
  laterpay/asset_sources/js/laterpay-post-edit.js
  laterpay/asset_sources/js/laterpay-post-view.js
  laterpay/asset_sources/scss/components/_purchase_overlay.scss
  laterpay/asset_sources/scss/laterpay-options.scss
  laterpay/asset_sources/scss/pages/_post_edit.scss
  laterpay/asset_sources/scss/pages/_pricing.scss
  laterpay/languages/laterpay-de_DE.mo
  laterpay/languages/laterpay-de_DE.po
  laterpay/languages/laterpay.po
  laterpay/laterpay.php
  laterpay/views/backend/partials/post-pricing-form.php
  laterpay/views/backend/pricing.php
  laterpay/views/frontend/partials/widget/purchase-overlay.php
  package.json
  ruleset.xml
Labels: v2.2.0
